# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2031ff882a065151ffdc2270d3018c39f67e670e4d08bb245d19c2d291d88fc85de674d2c6ab2fb9678ce1970daf518628c719efd17a0f24c89e51b433ecf74


test:
  secret_key_base: c6ccd18cb7b74f0b6105a39a1d27f9e143c63545ca7293848800de09195468d8e17f685f8d0353b9f155836c18b7f7681b3106eb1b02ee0581bc5828eea87bc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


  key_google_places: AIzaSyAQUqcR77raDKIBe9K6OiQs-6afHgfUOi4 
  key_getswift_api: 09466af8-da12-4cb2-9f30-c0d24fb4243c

